version: "3.9"
services:
  app:
    image: go-server
    container_name: go-server
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6380:6379"
