version: "3.9"
services:
  app:
    image: go-server
    container_name: go-server
    build:
      context: .
      args:
        APP: ${APP}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6380:6379"
  mongo:
    image: mongo:5.0.23
    container_name: mongo
    ports:
      - "27018:27017"

